/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcoulator;

import java.awt.event.KeyEvent;


/**
 *
 * @author hp
 */
public class calc extends javax.swing.JFrame {
Double firstnum,secondnum,result;
String operations;
private Object math;
    private Object jbtn7;
    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jbt7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnaddition = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnpm = new javax.swing.JButton();
        jbtndivision = new javax.swing.JButton();
        jbtnSub = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnequal = new javax.swing.JButton();
        jbtnsquareroot = new javax.swing.JButton();
        jbtnbackspace = new javax.swing.JButton();
        jbtnc = new javax.swing.JButton();
        jbtnmultiply = new javax.swing.JButton();
        jbtnlog = new javax.swing.JButton();
        jbtnsin = new javax.swing.JButton();
        jbtnsinh = new javax.swing.JButton();
        jbtnpi = new javax.swing.JButton();
        jbtncosh = new javax.swing.JButton();
        jbtnround = new javax.swing.JButton();
        jbtnpow3 = new javax.swing.JButton();
        jbtntanh = new javax.swing.JButton();
        jbtncos = new javax.swing.JButton();
        jtbnhex = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jbtnbinay = new javax.swing.JButton();
        jbtntan = new javax.swing.JButton();
        jbtnpow2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtnlnx = new javax.swing.JButton();
        jbtnexp = new javax.swing.JButton();
        jbtnfact = new javax.swing.JButton();
        jbtnOct = new javax.swing.JButton();
        jbtnacos = new javax.swing.JButton();
        jbtnasin = new javax.swing.JButton();
        jbtnatan = new javax.swing.JButton();
        jbtnradian = new javax.swing.JButton();
        jbtndegree = new javax.swing.JButton();
        jbtncbrt = new javax.swing.JButton();
        jbtn10x = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jbt7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt7.setText("7");
        jbt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt7ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtndot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtndot.setText(".");
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtnaddition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnaddition.setText("+");
        jbtnaddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnadditionActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtnpm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnpm.setText("±");
        jbtnpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpmActionPerformed(evt);
            }
        });

        jbtndivision.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtndivision.setText("/");
        jbtndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivisionActionPerformed(evt);
            }
        });

        jbtnSub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSub.setText("-");
        jbtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnequal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnequal.setText("=");
        jbtnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnequalActionPerformed(evt);
            }
        });

        jbtnsquareroot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnsquareroot.setText("√");
        jbtnsquareroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsquarerootActionPerformed(evt);
            }
        });

        jbtnbackspace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnbackspace.setText("←");
        jbtnbackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackspaceActionPerformed(evt);
            }
        });

        jbtnc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnc.setText("c");
        jbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncActionPerformed(evt);
            }
        });

        jbtnmultiply.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnmultiply.setText("*");
        jbtnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiplyActionPerformed(evt);
            }
        });

        jbtnlog.setText("log");
        jbtnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogActionPerformed(evt);
            }
        });

        jbtnsin.setText("sin");
        jbtnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsinActionPerformed(evt);
            }
        });

        jbtnsinh.setText("sinh");
        jbtnsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsinhActionPerformed(evt);
            }
        });

        jbtnpi.setText("π");
        jbtnpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpiActionPerformed(evt);
            }
        });

        jbtncosh.setText("cosh");
        jbtncosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncoshActionPerformed(evt);
            }
        });

        jbtnround.setText("rund");
        jbtnround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnroundActionPerformed(evt);
            }
        });

        jbtnpow3.setText("x^3");
        jbtnpow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpow3ActionPerformed(evt);
            }
        });

        jbtntanh.setText("tanh");
        jbtntanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntanhActionPerformed(evt);
            }
        });

        jbtncos.setText("cos");
        jbtncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncosActionPerformed(evt);
            }
        });

        jtbnhex.setText("hex");
        jtbnhex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnhexActionPerformed(evt);
            }
        });

        jButton15.setText("cbr");

        jButton17.setText("x^y");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jbtnbinay.setText("bin");
        jbtnbinay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbinayActionPerformed(evt);
            }
        });

        jbtntan.setText("tan");
        jbtntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntanActionPerformed(evt);
            }
        });

        jbtnpow2.setText("x^2");
        jbtnpow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpow2ActionPerformed(evt);
            }
        });

        jButton1.setText("mod");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnlnx.setText("lnx");
        jbtnlnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlnxActionPerformed(evt);
            }
        });

        jbtnexp.setText("ex");
        jbtnexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexpActionPerformed(evt);
            }
        });

        jbtnfact.setText("!");
        jbtnfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfactActionPerformed(evt);
            }
        });

        jbtnOct.setText("octal");
        jbtnOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOctActionPerformed(evt);
            }
        });

        jbtnacos.setText("acos");
        jbtnacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnacosActionPerformed(evt);
            }
        });

        jbtnasin.setText("asin");
        jbtnasin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnasinActionPerformed(evt);
            }
        });

        jbtnatan.setText("atan");
        jbtnatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnatanActionPerformed(evt);
            }
        });

        jbtnradian.setText("radian");
        jbtnradian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnradianActionPerformed(evt);
            }
        });

        jbtndegree.setText("degree");
        jbtndegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndegreeActionPerformed(evt);
            }
        });

        jbtncbrt.setText("∛");
        jbtncbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncbrtActionPerformed(evt);
            }
        });

        jbtn10x.setText("10x");
        jbtn10x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn10xActionPerformed(evt);
            }
        });

        jButton2.setText("not");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("And");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("or");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("stamdard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("scientefic");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbt7)
                                    .addComponent(jbtnbackspace))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtn8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(jbtnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtn9)
                                    .addComponent(jbtnsquareroot)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtn1)
                                    .addComponent(jbtn4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(jbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn3)
                                    .addComponent(jbtn6))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnaddition))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtn0)
                            .addGap(13, 13, 13)
                            .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtnpm)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtndivision, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnequal)))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnOct, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtndegree, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtncbrt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnpi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtncos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnpow2)
                                            .addComponent(jbtnpow3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnacos))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtnround)
                                            .addComponent(jbtntan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtbnhex, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jbtnasin)
                                                .addGap(1, 1, 1)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnsinh)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtncosh)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtnlnx, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbtntanh)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jButton15)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbtnexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnfact, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtn10x, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnatan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnradian, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnbinay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnlog)
                            .addComponent(jbtnsin)
                            .addComponent(jbtnsinh)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnbackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnc)
                            .addComponent(jbtnsquareroot)
                            .addComponent(jbtnaddition))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt7)
                            .addComponent(jbtn8)
                            .addComponent(jbtn9)
                            .addComponent(jbtnSub))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnmultiply))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtndivision, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnpm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnlnx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtncosh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnexp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtntan)
                                        .addComponent(jbtntanh)
                                        .addComponent(jButton17))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnpi)
                                    .addComponent(jbtncos))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnpow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnfact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnOct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtbnhex)
                                    .addComponent(jButton4))
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtnpow3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnacos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnasin)
                                    .addComponent(jbtnatan)
                                    .addComponent(jbtnradian))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtndegree)
                                    .addComponent(jbtncbrt)
                                    .addComponent(jbtn10x, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jbtnbinay)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(260,400);
        
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         this.setResizable(true);
        this.setSize(260,400);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(550,500);
        jtxtDisplay.setSize(400,40);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt7ActionPerformed
        String iNum;
    iNum = jTextField1.getText()+ jbt7.getText();
        jTextField1.setText(iNum);
    }//GEN-LAST:event_jbt7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
         String iNum;
    iNum = jTextField1.getText()+ jbtn8.getText();
        jTextField1.setText(iNum);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
      String iNum;
    iNum = jTextField1.getText()+ jbtn9.getText();
       jTextField1.setText(iNum);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
       String iNum;
    iNum = jTextField1.getText()+ jbtn0.getText();
        jTextField1.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
String iNum;
    iNum = jTextField1.getText()+ jbtn1.getText();
        jTextField1.setText(iNum);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
String iNum;
    iNum =jTextField1.getText()+ jbtn3.getText();
        jTextField1.setText(iNum);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
String iNum;
    iNum = jTextField1.getText()+ jbtn4.getText();
       jTextField1.setText(iNum);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
       
        String iNum;
    iNum =jTextField1.getText()+ jbtn5.getText();
        jTextField1.setText(iNum);// TODO add your handling code here:
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
String iNum;
    iNum = jTextField1.getText()+ jbtn6.getText();
        jTextField1.setText(iNum);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jbtncActionPerformed

    private void jbtnbackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackspaceActionPerformed
       String bsp=null;
       
       if(jTextField1.getText().length()>0)
       {
           StringBuilder strB=new StringBuilder(jTextField1.getText());
           strB.deleteCharAt(jTextField1.getText().length()-1);
           bsp=strB.toString();
           jTextField1.setText(bsp);
       }// TODO add your handling code here:
    }//GEN-LAST:event_jbtnbackspaceActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
       if(!jTextField1.getText().contains("."))
       {
       jTextField1.setText(jTextField1.getText()+jbtndot.getText());
       }
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtnpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpmActionPerformed
        double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=ops*(-1);
        jTextField1.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_jbtnpmActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jbtnsquarerootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsquarerootActionPerformed
 double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.sqrt(ops);
        jTextField1.setText(String.valueOf(ops));        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnsquarerootActionPerformed

    private void jbtnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.log(ops);
        jTextField1.setText(String.valueOf(ops)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnlogActionPerformed

    private void jbtnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsinActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.sin(ops);
        jTextField1.setText(String.valueOf(ops));         
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnsinActionPerformed

    private void jbtnsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsinhActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.sinh(ops);
        jTextField1.setText(String.valueOf(ops));   
        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnsinhActionPerformed

    private void jbtncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncosActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.cos(ops);
        jTextField1.setText(String.valueOf(ops));         // TODO add your handling code here:
    }//GEN-LAST:event_jbtncosActionPerformed

    private void jbtncoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncoshActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.cosh(ops);
        jTextField1.setText(String.valueOf(ops));         // TODO add your handling code here:
    }//GEN-LAST:event_jbtncoshActionPerformed

    private void jbtntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntanActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.tan(ops);
        jTextField1.setText(String.valueOf(ops));         // TODO add your handling code here:
    }//GEN-LAST:event_jbtntanActionPerformed

    private void jbtntanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntanhActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.tanh(ops);
        jTextField1.setText(String.valueOf(ops));         // TODO add your handling code here:
    }//GEN-LAST:event_jbtntanhActionPerformed

    private void jbtnpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpiActionPerformed
        double ops;// Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=(3.14);
        jTextField1.setText(String.valueOf(ops)); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnpiActionPerformed

    private void jbtnroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnroundActionPerformed
     
        double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.round(ops);
        jTextField1.setText(String.valueOf(ops)); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnroundActionPerformed

    private void jbtnpow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpow3ActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.pow(ops,3);
        jTextField1.setText(String.valueOf(ops));         // TODO add your handling code here:
    }//GEN-LAST:event_jbtnpow3ActionPerformed

    private void jbtnpow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpow2ActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.pow(ops,2);
        jTextField1.setText(String.valueOf(ops));         // TODO add your handling code here:
    }//GEN-LAST:event_jbtnpow2ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.pow(ops,ops);
        jTextField1.setText(String.valueOf(ops)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jbtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequalActionPerformed
       String answer;
       secondnum = Double.parseDouble(jTextField1.getText());
    switch (operations) {
        case "+":
            result = firstnum + secondnum;
            answer = String.format("%.2f",result);
            jTextField1.setText(answer);
            break;
        case "-":
            result = firstnum - secondnum;
            answer = String.format("%.2f",result);
            jTextField1.setText(answer);
            break;
        case "*":
            result = firstnum * secondnum;
            answer = String.format("%.2f",result);
            jTextField1.setText(answer);
            break;
        case "/":
            result = firstnum / secondnum;
            answer = String.format("%.2f",result);
            jTextField1.setText(answer);
            break;
        case "%":
            result = firstnum % secondnum;
            answer = String.format("%.2f",result);
            jTextField1.setText(answer);
            break;
              case "And":
            result = Math.max(firstnum , secondnum);
            answer = String.format("%.2f",result);
            jTextField1.setText(answer);
            break;
                  case "OR":
            result = Math.max(firstnum , secondnum);
            answer = String.format("%.2f",result);
            jTextField1.setText(answer);
            break;
    }
    }//GEN-LAST:event_jbtnequalActionPerformed

    private void jbtndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivisionActionPerformed
        firstnum = Double.parseDouble(jTextField1.getText());  
  jTextField1.setText(null);
  operations=("/");
    }//GEN-LAST:event_jbtndivisionActionPerformed

    private void jbtnadditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnadditionActionPerformed
firstnum = Double.parseDouble(jTextField1.getText());  
  jTextField1.setText(null);
  operations=("+");
    }//GEN-LAST:event_jbtnadditionActionPerformed

    private void jbtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplyActionPerformed
firstnum = Double.parseDouble(jTextField1.getText());  
  jTextField1.setText(null);
  operations=("*");
    }//GEN-LAST:event_jbtnmultiplyActionPerformed

    private void jbtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubActionPerformed
firstnum = Double.parseDouble(jTextField1.getText());  
  jTextField1.setText(null);
  operations=("-");
    }//GEN-LAST:event_jbtnSubActionPerformed

    private void jbtnbinayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbinayActionPerformed
int a=Integer.parseInt(jTextField1.getText());   //binary
jTextField1.setText(Integer.toString(a,2)); 
    }//GEN-LAST:event_jbtnbinayActionPerformed

    private void jtbnhexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnhexActionPerformed
int a=Integer.parseInt(jTextField1.getText());  //hexadicimal 
jTextField1.setText(Integer.toString(a,16));        
// TODO add your handling code here:
    }//GEN-LAST:event_jtbnhexActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
    char c=evt.getKeyChar();
    if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)
      || (c == KeyEvent.VK_DELETE))){
      getToolkit().beep();
      evt.consume();
    }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jbtnOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOctActionPerformed
     int a=Integer.parseInt(jTextField1.getText());  
jTextField1.setText(Integer.toString(a,8)); 
    }//GEN-LAST:event_jbtnOctActionPerformed

    private void jbtnlnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlnxActionPerformed
 double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.log10(ops);
        jTextField1.setText(String.valueOf(ops));        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnlnxActionPerformed

    private void jbtnexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexpActionPerformed
       double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.exp(ops);
        jTextField1.setText(String.valueOf(ops));    // TODO add your handling code here:
    }//GEN-LAST:event_jbtnexpActionPerformed

    private void jbtnacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnacosActionPerformed
       double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.acos(ops);
        jTextField1.setText(String.valueOf(ops));  // TODO add your handling code here:
    }//GEN-LAST:event_jbtnacosActionPerformed

    private void jbtnasinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnasinActionPerformed
       double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.asin(ops);
        jTextField1.setText(String.valueOf(ops));  // TODO add your handling code here:
    }//GEN-LAST:event_jbtnasinActionPerformed

    private void jbtnatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnatanActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.atan(ops);
        jTextField1.setText(String.valueOf(ops));         // TODO add your handling code here:
    }//GEN-LAST:event_jbtnatanActionPerformed

    private void jbtnfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfactActionPerformed
int i,n;
int fact =1;
n=Integer.parseInt(jTextField1.getText());
for(i=n;i>=1;i--){
    fact*=i;
}
jTextField1.setText(Integer.toString(fact));
    }//GEN-LAST:event_jbtnfactActionPerformed

    private void jbtnradianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnradianActionPerformed
      double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.toRadians(ops);
        jTextField1.setText(String.valueOf(ops));   // TODO add your handling code here:
    }//GEN-LAST:event_jbtnradianActionPerformed

    private void jbtndegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndegreeActionPerformed
double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.toDegrees(ops);
        jTextField1.setText(String.valueOf(ops));         // TODO add your handling code here:
    }//GEN-LAST:event_jbtndegreeActionPerformed

    private void jbtncbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncbrtActionPerformed
       double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.cbrt(ops);
        jTextField1.setText(String.valueOf(ops));  // TODO add your handling code here:
    }//GEN-LAST:event_jbtncbrtActionPerformed

    private void jbtn10xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn10xActionPerformed
        double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=Math.pow(10, ops);
        jTextField1.setText(String.valueOf(ops));  // TODO add your handling code here:
    }//GEN-LAST:event_jbtn10xActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
firstnum = Double.parseDouble(jTextField1.getText());  
  jTextField1.setText(null);
  operations=("And");       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       firstnum = Double.parseDouble(jTextField1.getText());  
  jTextField1.setText(null);
  operations=("OR"); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       double ops= Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops=-+(ops-1);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
String iNum;
    iNum = jTextField1.getText()+ jbtn2.getText();
        jTextField1.setText(iNum);         // TODO add your handling code here:
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       firstnum = Double.parseDouble(jTextField1.getText());  
  jTextField1.setText(null);
  operations=("%");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbt7;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn10x;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnOct;
    private javax.swing.JButton jbtnSub;
    private javax.swing.JButton jbtnacos;
    private javax.swing.JButton jbtnaddition;
    private javax.swing.JButton jbtnasin;
    private javax.swing.JButton jbtnatan;
    private javax.swing.JButton jbtnbackspace;
    private javax.swing.JButton jbtnbinay;
    private javax.swing.JButton jbtnc;
    private javax.swing.JButton jbtncbrt;
    private javax.swing.JButton jbtncos;
    private javax.swing.JButton jbtncosh;
    private javax.swing.JButton jbtndegree;
    private javax.swing.JButton jbtndivision;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtnequal;
    private javax.swing.JButton jbtnexp;
    private javax.swing.JButton jbtnfact;
    private javax.swing.JButton jbtnlnx;
    private javax.swing.JButton jbtnlog;
    private javax.swing.JButton jbtnmultiply;
    private javax.swing.JButton jbtnpi;
    private javax.swing.JButton jbtnpm;
    private javax.swing.JButton jbtnpow2;
    private javax.swing.JButton jbtnpow3;
    private javax.swing.JButton jbtnradian;
    private javax.swing.JButton jbtnround;
    private javax.swing.JButton jbtnsin;
    private javax.swing.JButton jbtnsinh;
    private javax.swing.JButton jbtnsquareroot;
    private javax.swing.JButton jbtntan;
    private javax.swing.JButton jbtntanh;
    private javax.swing.JButton jtbnhex;
    // End of variables declaration//GEN-END:variables
}
